### ISSUE TITLE
Differentiating between the two admixr packages

### ISSUE THREAD

**Issue by s-usr** [bodkan/admixr#46]
There are two admixr packages; yours based on AdmixTools (Harvard) and the Sikora's based on Admixture (UCLA). When insalling, one will overwrite the other. Is that correct?  Is there a way to avoid this?

**Comment by bodkan** [comment]
This issue has been open for so long with no progress that I feel it's best to close it.

If someone runs into this problem (I am not sure how widely used the _admixr_-ADMIXTURE package is, given that it hasn't been updated for 6 years), it is possible to install both packages by:

1. Installing this _admixr_ package (the ADMIXTOOLS version) as you normally would.
2. Running `git clone https://github.com/martinsikora/admixr` to download the ADMIXTURE package anywhere on your computer that's convenient for you.
3. Manually editing the [DESCRIPTION file](https://github.com/martinsikora/admixr/blob/master/DESCRIPTION#L1) in the downloaded copy to some other name (such as 'ADMIXTURE', for instance).
4. Running `devtools::install("path to the downloaded copy")` will install the ADMIXTURE package under the modified name.
5. Running
```
library(admixr)
library(ADMIXTURE)
```
will load both packages without any issue.
