### ISSUE TITLE
Passing Params to PAR File

### ISSUE THREAD

**Issue by testeranon** [bodkan/admixr#50]
Hi unable to send special parameters to the par file using the params argument.

for example in qpWave or qpAdm, param = "allsnps : Yes" is not passed into the actual PAR file.

**Comment by bodkan** [comment]
Hi,

can you try specifying the option with `params = list(allsnps = "YES"))`? The reason it's done in this (rather cumbersome, I admit) way is that it allows to specify multiple options at once.

There might be a better way of doing this in the future...

**Comment by bodkan** [comment]
Let me know if this works for you!

**Comment by testeranon** [comment]
Perfect!

Also i hear you. the list option is the best way to send multiple params to the PAR file.

However only change in future, if you will, could be allowing single param without the list option.
