### ISSUE TITLE
An error returning empty dataframe

### ISSUE THREAD

**Issue by aromaze85** [bodkan/admixr#55]
I have an issue supposed to be bad input format files but I checked everyting I could :
I get such an error:
"
fatalx:
(ineigenstrat) too many lines in file 200 200
Aborted
Warning message:
ADMIXTOOLS does not allow duplicated population names when calculating a single f4 or D statistic.
Returning an empty dataframe...
"
I looked on the web, such an error is supposed to be the number of genotypes that does not correspond to the number of individuals under study.
However, here I have the same number: 200 and 200

My ind file (200 rows, first 2 pops Ind\~TD and Ind\~LF (each one has 2 individuals) are shown) looks like:
"
Ind\~TD\~1\~1 U Ind\~TD
Ind\~TD\~1\~2 U Ind\~TD
Ind\~LF\~1\~1 U Ind\~LF
Ind\~LF\~1\~2 U Ind\~LF
...
"
My snp file (300 rows):
"
rs1 1 0.1 1 A T
rs2 1 0.2 2 A T
rs3 1 0.3 3 A T
...
"
My geno file (300 rows, 200 columns)
"
0121010001...
0200021000...
...
"
My R script runned in the src folder of Admixtools:
"
library(admixr)
setwd("/home/DATA")
prefix <- "/home/DATA/example"
list.files(path = dirname(prefix), pattern = basename(prefix), full.names = TRUE)
snps <- eigenstrat(prefix)
pops <- c("Ind\~TD") ; result <- d(W = pops, X = "Ind\~LF", Y = "Ind\~DR", Z = "Ind\~GH", data=snps)
"

What could go wrong?

Thanks.

**Comment by bodkan** [comment]
Hi,

In case your example data is really so small (300 rows), do you think you could paste it in here? It is possible to attach files to Github issues. Alternatively, if you don't want to share it publicly, maybe you could send it to my email at contact[AT-SIGN-HERE]bodkan.net.

The error is a bit hard to understand - but it's clearly ADMIXTOOLS having an issue, not the admixr package itself.

**Comment by bodkan** [comment]
The issue was resolved via email. The problem turned out to be a data processing error unrelated to admixr or ADMIXTOOLS.
