### ISSUE TITLE
ROLLOFF 

### ISSUE THREAD

**Issue by foala** [bodkan/admixr#66]
Hi,
Thank you very much for this great tool.
May I know if admixtools ROLLOFF is implemented in admixr?
Thank you,

**Comment by bodkan** [comment]
Hi,

I'm sorry to say that ROLOFF is not implemented and currently it's not even on the roadmap. In principle it shouldn't be difficult to implement it. In fact, anyone with a bit of R knowledge should be able to copy one of admixr's wrapper functions and change the necessary parts to work with ROLOFF, including a dedicated parser function. This could easily be added to the package. Unfortunately, I have no capacity to do that myself. I'd be very happy if someone did it and opened a pull request.

That said, may I direct you to this comment from Nick Patterson suggesting an improved, alternative tool? https://github.com/DReichLab/AdmixTools/blob/master/README.ROLLOFF#L70 I have no experience with it though...

Thank you for being interested in my package, I'm glad you find it useful.

I'm going to close the issue and reopen it in case there are future developments in this regard (you should get a Github notification when that happens).
