### ISSUE TITLE
AABB/BBAA sites

### ISSUE THREAD

**Issue by qhelleu** [bodkan/admixr#74]
Hi,

AdmixR is a great tool, I used it a lot recently. But I wonder if it would be possible to add the number of AABB/BBAA sites for each comparison? They are a great source of information, as they should, in theory, match the species tree. 
Thanks,
Best.

**Comment by bodkan** [comment]
Hi @qhelleu,

Thank you for being interested in my package.

I agree, I have often wondered about this as this is something even people in our lab sometimes need.

Unfortunately, admixr can only present information which is provided by the underlying ADMIXTOOLS package. And, as far as I know, there is currently no parameter in ADMIXTOOLS that can make it return these counts.

Maybe you could raise this issue on their [Github issue page](https://github.com/DReichLab/AdmixTools/issues/)?

If that's ever implemented in ADMIXTOOLS, I'd be happy to immediately add it to the admixr package.

Feel free to let me know if you find out there has been a development on this issue in the future.
