### ISSUE TITLE
Outgroup f3

### ISSUE THREAD

**Issue by murielgb** [bodkan/admixr#76]
Hi Peter!

Thank you again for the package!

I have a question related to f3 stats.

I used it the standard way to test whether a population C is admixed between A and B. Did this:
`f3(data=snps, A=popA, B=popB, C=popC)`

But I also wanted to calculate the outgroup-f3, to get a measure of differentiation between the admixing species and the admixed species (individual basis).
I though what I could do is (compared to the above standard way):
```
C= outgroup to the two species
A= admixing species (all samples)
B= admixed species (one sample at a time)
```

Is that the correct way of implementing outgroup-f3 in admixr?

But, looking at how to do outgroup-f3 with ADMIXTOOLS (since your package is an implementation of it), I found this:
```
*** NEW *** 
By default f_3 output is normalized by estimatated heterozygosity 
of the target.   This doesn't work if the target has no hets as can 
happen in "outgroup f_3" mode.  In this case set:
outgroupmode: YES
when the f-3 denominator is set to an arbitrary .001
```
Here: https://github.com/DReichLab/AdmixTools/blob/master/README.3PopTest#L34

But my understanding is that currently, in the admixr package, there is no option outgroupmode. Does that mean I cannot do outgroup-f3 with admixr? Ot maybe you have a solution?

Thanks a lot!!

Muriel

**Comment by bodkan** [comment]
Hello Muriel,

You can provide optional parameters via a generic `params =` argument of each _admixr_ function.

Example can be found [here](https://github.com/bodkan/admixr/issues/73#issuecomment-684783535) (this relates to a different optional parameter of ADMIXTOOLS but the idea is the same).

So, to do this for the `outgroupmode` you could then specify `params = list(outgroupmode = "YES")` in an analogous way. Let me know if this works, as I have never used this particular parameter. You could test if it was specified properly by [examining the full log information](https://bodkan.net/admixr/articles/tutorial.html#examining-log-information-1) on the returned f3 object and checking that the parameter is really there.

Best regards,
Martin

**Comment by murielgb** [comment]
Hi Peter!

Great, I will try this today or tomorrow and will met you know the outcome!

I have a question though, related to the method.
Should populations A and B be equally distant from population C to have a reliable f3?

Thanks!

Muriel

**Comment by murielgb** [comment]
That worked perfectly, thanks a lot Peter!!

**Comment by bodkan** [comment]
Wonderful! Glad to hear that.

With regards to your _f3_ question, I personally don't think this is a requirement. For a more theoretical treatment of _f_-statistics and their limiting properties, I highly recommend the amazing [overview](https://www.genetics.org/content/202/4/1485) by Benjamin Peter. I'm sure you will find a definitive answer there.

Good luck!

(It's Martin, by the way. 😅 )

**Comment by bodkan** [comment]
Closing this issue, because it seems that we managed to solve the problem. :)

**Comment by murielgb** [comment]
Thanks Martin!! 
Sorry for not using your actual first name😵!

**Comment by bodkan** [comment]
No worries. :)
