### ISSUE TITLE
bad chrom: conting111,The number of genome conting more than 1000?

### ISSUE THREAD

**Issue by biofang** [bodkan/admixr#78]
Hi!
Thanks for this nice package for D statistic!

 I used it a lot recently，but my genome assembly is conting level！How should I change the QTP.snp file format to make it run normally.

bad chrom:  conting111
sh: line 1:  2481 Aborted                 (core dumped) qpDstat -p /tmp/RtmpeaOmOF/qpDstat__1610545810.par > /tmp/RtmpeaOmOF/qpDstat__1610545810.log
BEGINNING OF OUTPUT FILE
==================================================

qpDstat: parameter file: /tmp/RtmpeaOmOF/qpDstat__1610545810.par
### THE INPUT PARAMETERS
##PARAMETER NAME: VALUE
genotypename: QTP.geno
snpname: QTP.snp
indivname: QTP.ind

Any advice on that?

Thanks!

**Comment by bodkan** [comment]
Apologies for keeping this open for this long.

For future reference (this is not the first time this issue popped up), I’m afraid this is not an admixr error, but rather a limitation of ADMIXTOOLS itself.

Searching for contig-related issues among closed issues here or in the ADMIXTOOLS repository will give more context (mostly w.r.t. problem with calculating std errors from the block jackknife).
