### ISSUE TITLE
f4 stats all zero.  Rank 0!.  Aborting run

### ISSUE THREAD

**Issue by sahwa** [bodkan/admixr#80]
Hi,

I am trying to use qpWave to estimate the number of ancestry waves between modern and ancient populations:

```
result = qpWave(
	left = c("croatian", "polish", "lithuanian", "ukrainian"),
	right = c("ancient_pop_1"),
	data = snps
)
```
It produced this output file: 

```
BEGINNING OF OUTPUT FILE
==================================================

qpWave: parameter file: /tmp/Rtmp240xNl/qpWave__1135274880.par
### THE INPUT PARAMETERS
##PARAMETER NAME: VALUE
genotypename: /home/sam/Dropbox/Documents/PhD/PhD/analyses/slavs/results_II/qpwave/data/example.geno
snpname: /home/sam/Dropbox/Documents/PhD/PhD/analyses/slavs/results_II/qpwave/data/example.snp
indivname: /home/sam/Dropbox/Documents/PhD/PhD/analyses/slavs/results_II/qpwave/data/example.ind
popleft: /tmp/Rtmp240xNl/qpWave__1135274880.popleft
popright: /tmp/Rtmp240xNl/qpWave__1135274880.popright
## qpWave version: 1520
allsnps set NO.  It is recommended that allsnps be set explicitly
 *** recommended that inbreed be explicitly set ***
inbreed set NO

left pops:
croatian
polish
lithuanian
ukrainian

right pops:
ancient_pop_1

  0             croatian   19
  1               polish   17
  2           lithuanian   10
  3            ukrainian   20
  4            ancient_pop_1    5
jackknife block size:     0.050
snps: 448637  indivs: 71
number of blocks for block jackknife: 534
Effective number of blocks:   477.804
numsnps used: 448637
f4 stats all zero.  Rank 0!.  Aborting run
```
I am not too experienced with qpWave, but I suspect it could be caused by only using a single right population? I tested adding in a different unrelated ancient population as an additional right population and the error disappearance. 

Other than that, do you know what might be causing this. Please let me know if you need more information.

Thank you.

**Comment by bodkan** [comment]
Hello, I don't think using a single "right" population makes sense for a qpWave test if you want to test the number of admixture waves? By doing this, you provide essentially only one population for testing this? It's been a long time since I did any qpWave work, but I'm not surprised you get an error (I do agree that ADMIXTOOLS could be a little bit more explicit in its error reporting here, especially for newer users).

**Comment by bodkan** [comment]
What I could do is to implement such a check myself and write an error on the _admixr_ side that is a bit more helpful. It has been a long time since I released a new version anyway and there were some improvements that I should add too. I can add this to my to do list.

**Comment by bodkan** [comment]
Given that this issue does not involve an _admixr_ bug and that it seems that we resolved it, I will close this for now. Feel free to open another issue if you run into some bugs.

For more general questions about qpWave best practices, I recommend asking on the official [ADMIXTOOLS](https://github.com/DReichLab/AdmixTools/) Github page.

**Comment by sahwa** [comment]
Hi - thanks for the tip - nn hindsight I agree it doesn't make sense to use a single right population. 

Best, Sam
