### ISSUE TITLE
filter the geno file for transitions

### ISSUE THREAD

**Issue by mariels** [bodkan/admixr#81]
Hello,
I have been using the transversions_only function to find the SNPs to exclude to remove transitions in aDNA data. I was wondering if there was any built in function to filter the geno file at the same time?
Otherwise I guess identify which line numbers are to be excluded in the snp file and then removing those in the geno file should work.
Thanks,
Marie

**Comment by bodkan** [comment]
Hello Marie,

The function `transversions_only` returns a modified EIGENSTRAT data set, with SNPs appropriately filtered. That is, the data set includes what ADMIXTOOLS calls a `badsnp` file, telling it which sites to remove in the process.

See this example:

```
> library(admixr)
> snps <- eigenstrat(download_data())
> snps
EIGENSTRAT object
=================
components:
  ind file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.ind
  snp file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.snp
  geno file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.geno
> 
> tv_snps <- transversions_only(snps)
> tv_snps
EIGENSTRAT object
=================
components:
  ind file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.ind
  snp file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.snp
  geno file: /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/snps/snps.geno

modifiers:
  excluded sites:  /var/folders/hr/_t1b0f5n7c76yrfsg8yk9l100000gn/T//RtmpQnLBg9/filee415781467e0.snp 
      (SNPs excluded: 1, SNPs remaining: 499999)
```

In this case, if you would run something like `d(data = tv_snps, ...)`, the D statistic will be calculated only on transversions only.

Does this help?

**Comment by mariels** [comment]
Hi Martin,

Great, many thanks, I did not realise the generated "badnsp" file could be used directly in Admixtools, that is what I was looking for (to also run qpgraph).

All the best,

Marie

**Comment by bodkan** [comment]
Yes, I simply named this file "excluded sites" because it seemed more reasonable than just `badsnp`. Sorry that it actually confused you instead! What the package is doing with `transversions_only` or `filter_bed` in general is all using `badsnp` files under the hood.

Good luck! Closing this issue because it seems we resolved it.
