### ISSUE TITLE
pop:  has sample size 1 and inbreed set

### ISSUE THREAD

**Issue by sahwa** [bodkan/admixr#82]
Hi again,

Apologies if this issue is in the documentation - I had a look and couldn't find anything. I'm running into an error when using qpAdm:

```
result = admixr::qpAdm(
	target = c("Middle_Neolithic_France"),
	sources = c("WHG", "Yamnaya", "Anatolia_Neolithic"),
	outgroups = c("sannamibia", "Mota", "mbutipygmy", "papuan", "hannchina", "pima"),
	data = snps
)
```
```
fatalx:
pop: Mota has sample size 1 and inbreed set
Aborted (core dumped)
Segmentation fault (core dumped)
BEGINNING OF OUTPUT FILE
==================================================

qpAdm: parameter file: /tmp/Rtmp1aWf7j/qpAdm__2042662743.par
### THE INPUT PARAMETERS
##PARAMETER NAME: VALUE
genotypename: /xx/example.geno
snpname: xx/example.snp
indivname: xx/example.ind
popleft: /tmp/Rtmp1aWf7j/qpAdm__2042662743.popleft
popright: /tmp/Rtmp1aWf7j/qpAdm__2042662743.popright
allsnps: YES
summary: YES
details: YES
```

The error message seems clear that it doesn't like the fact that one of the populations contains only a single individual and (maybe) the ``inbreed`` parameter is set to TRUE/1. Is it possible to turn inbreed off when using qpAdm? It doesn't seem to be an option for the qpAdm function. If not, is there a way to make qpAdm ignore the error?

It definitely seems possible to use Mota as an outgroup as it was used in [this paper](https://static-content.springer.com/esm/art%3A10.1038%2Fnature25738/MediaObjects/41586_2018_BFnature25738_MOESM2_ESM.pdf). 

Thanks.

**Comment by bodkan** [comment]
Hello, the general way to change ADMIXTOOLS parameters from each _admixr_ functions is via the `params = ` argument. See example [here](https://github.com/bodkan/admixr/issues/76#issuecomment-704224526) which involved changing a different parameter and the documentation [here](https://bodkan.net/admixr/reference/f4ratio.html).
