### ISSUE TITLE
admixr does not find qpDstat

### ISSUE THREAD

**Issue by nicolo-tellini** [bodkan/admixr#89]
Dear @bodkan , 

I am running admixtools v.7.0.2  and  admixr v.0.9.1
I am using the d function but I am getting the following error:

`
sh: qpDstat: command not found
Warning in system(paste(cmd, "-p", par_file, ">", log_file)) :
  error in running command
BEGINNING OF OUTPUT FILE

END OF OUTPUT FILE

Error: The output file we got from ADMIXTOOLS is truncated.
       Please examine the full output above and check for errors.
` 

This is a bit confusing because qpDstat is already in my $PATH : 

`[ntellini@hulk AMH]$ which qpDstat 
`

output 

`/home/tools/bin/qpDstat`

my $PATH : 

`[ntellini@hulk AMH]$ echo $PATH | grep "/home/tools/bin"
`

`[...]/home/tools/bin[...]
`

Am I missing something ?

thanks, 

best regards,

nic

**Comment by nicolo-tellini** [comment]
Hi, 

I have just read issue #33  

I have not run :  'echo \"PATH=$PATH\" >> .Renviron' in the shell, yet.

I will try and, in case, close the issue. 

Thanks,

nic

**Comment by nicolo-tellini** [comment]
Dear @bodkan,

I solved the problem following #33. 
I would also add, in the comment at #33, that for loading .Renviron is necessary running (in R)

`readRenviron(path = ".Renviron")`

assuming that .Renviron is in the `wd()`. 
This can be useful given that loading .Renviron is an uncommon task. 

best regards,

nic

**Comment by bodkan** [comment]
Hello. Glad to hear you've arrived at a solution.

Just for completeness, normally you would use an `~/.Renviron` file. I.e., put the file in your `$HOME` directory, not in your working directory. That way, R loads it automatically upon startup, setting up the path for each R session. No additional work is necessary.

Using `~/.Renviron` (or, similarly, `~/.Rprofile`) file is actually very common.

(That said, thank you for pointing out the existence of the `readEnviron` function. I've been using R for > 10 years and I wasn't aware of this function. :))
