### ISSUE TITLE
Error in F3: Following samples are not present

### ISSUE THREAD

**Issue by ans6160** [bodkan/admixr#90]
Hi, 

I am trying to run the f3 command over a large data set and I keep getting this error that says the following populations are not present in the data. The .snp/.ind/.geno files are all in eigenstrat format and if I were to open the files in the terminal, I see exactly what you expect to see. I was following the tutorial, but I am not sure what I am doing wrong. 

Here is the code that produces the error: 
prefix<- "~/Downloads/AADR_datasets/F3_stats_group/f3_aDNA_subset"
pre<- eigenstrat(prefix)
pre #gives me the eigenstrat object

#pops
pops<-setDT(list(final_ind$V3))
testRes<- f3(A=pops, B=pops, C = "Ignore_Mbuti(discovery).DG", data = pre)

Hopefully this description makes sense.

**Comment by ans6160** [comment]
I figured out what was wrong. I was not specifying the column in pops.

**Comment by bodkan** [comment]
Great! :) Thanks for reporting back and thanks for using admixr!
